apiVersion: v1
description: Prometheus instance created by the CoreOS Prometheus Operator
engine: gotpl
maintainers:
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
name: prometheus
sources:
  - https://gitlab.300.cn/paas-k8s/prometheus-operator
version: 0.0.51

