description: Grafana instance for kube-prometheus
engine: gotpl
maintainers:
- email: weiwei.inf@gmail.com
  name: Wei Wei
- email: vglafirov@gmail.com
  name: Vladimir Glafirov
name: grafana
sources:
- https://gitlab.300.cn/paas-k8s/prometheus-operator
version: 0.0.37
