description: Grafana instance for kube-prometheus
engine: gotpl
maintainers:
- email: weiwei.inf@gmail.com
  name: Wei Wei
- email: vglafirov@gmail.com
  name: Vladimir Glafirov
name: grafana
sources:
- https://github.com/zhonglin6666/prometheus-operator
version: 0.0.37
